#!/bin/bash

chown -R nginx:www-data \
  /var/lib/nginx


#envsubst < /etc/templates/yii2nginx.conf.tmpl > /etc/nginx/presets/default.conf

sed -i "s/frontend.dev/${HOST_FRONT}/" /etc/nginx/presets/default.conf
sed -i "s/backend.dev/${HOST_BACK}/" /etc/nginx/presets/default.conf